version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    command: sh -c "cd src/tasks && celery -A celery_config.celery_app worker --loglevel=info"
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    command: sh -c "cd src/tasks && celery -A celery_config.celery_app beat --loglevel=info"
  redis:
    image: "redis:latest"
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: phishGuardDB
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: